name: Reusable Workflow Caller

on:
  push:

jobs:
  Reusable-caller-job:
    uses: ./.github/workflows/maven-cache.yml
    # uses: mynameismishu/SpringBootDocker/.github/workflows/maven-cache.yml@master
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SSH_HOST_USER: ${{ secrets.SSH_HOST_USER }}
      SSH_HOST_PASS: ${{ secrets.SSH_HOST_PASS }}
