name: Docker image Build Process

on:
  workflow_dispatch:
  workflow_call:

jobs:
  docker:
    env:
     appName: "springboot-image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.appName }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: Deploy Application using SSH
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
       WELCOME: "ssh scp ssh pipelines"
       LASTSSH: "Doing something after copying"
      with:
       host: '3.93.199.127'
       user: 'mihaipodaruvoda'
       pass: 'ruvoda0A@bnksm'
       port: 42006
       connect_timeout: 10s
       first_ssh: |
        rm -rf /tmp/Docker
        mkdir -p /tmp/Docker
       scp: |
        'Dockerfile' => /tmp/Docker
       last_ssh: |
        docker run -d ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.appName }}:latest

